### PR TITLE
for loops are now generated inline rather than in an IIFE

### PR DESCRIPTION
**Pull request by alubbe**
will need the lexer update that generates unique keys to work

### CODE REVIEW

**Comment by ForbesLindesay** [comment]
We should generate the unique indexes in the compiler (if they are needed) because the compiler can maintain a unique index over the output code, but lexers are per input file.

**Comment by ForbesLindesay** [comment]
Let's also change all variables to be `jade_` prefixed to indicate they are internal.

**Comment by alubbe** [comment]
Done

**Comment by alubbe** [comment]
Updated to reflect https://github.com/jadejs/jade/pull/1983, should be ready to be merged

**Comment by TimothyGu** [comment]
@alubbe, looks good to me. Merge any time.

**Pull request merged**
