### PR TITLE
Revert #1 "for loops are now generated inline"

### PR DESCRIPTION
**Pull request by TimothyGu**
This reverts commit 8ef3f8c2464ff5cf9b2fafb6455507fc034a66d6, reversing changes made to 82f11b75bce05c03c5980c90fcb3d2ca396ec237.

Fixes pugjs/pug#2365.
Closes #24.

CC: @alubbe

### CODE REVIEW

**Comment by ForbesLindesay** [comment]
If I recall correctly, this had a huge performance hit.  I wonder if there is either:
1. another way we could do this
2. this is worth having as a breaking change

Long run we could rename the inner variable name to prevent it conflicting, but that would make compilation much slower.  It's also a lot of work

**Comment by jeromew** [comment]
I guess that people that are masking the global `foo`variable are not expecting it to be accessible inside the loop.

the global `foo`value  could maybe be saved in a tmp variable at the beginning of the loop and re-affected to `foo` at the end. (?)

**Comment by TimothyGu** [comment]
@ForbesLindesay 

> another way we could do this

We _could_ try to use arrow functions, which would avoid the need of `.call(this)` (the source of a major performance hit), but that isn't currently an option.

@jeromew, this bug has something to do with the `with` module, which is the mechanism by which we scan all variables used in the template and make them available from locals. Because we redeclare the variable for the loop with `var`, and `var` declarations are hoisted in the template function, the `with` module doesn't treat the variable as a local.

**Comment by alubbe** [comment]
Maybe I can help in providing context for the original change - it was part of a larger performance investigation and, out of the 4 PRs that came out of it, it had the smallest runtime improvement (see https://github.com/pugjs/pug/issues/1975). 

Thus, my personal feeling would be that if there is a "simple" way of fixing this (e.g., renaming variables in for-loop scopes by appending random suffixes), I think it would be worth pursuing that - but if no such simple solution exists or the solutions are too complex to implement, I would be in favour of reverting the feature/merging this PR.

**Comment by feross** [comment]
I appreciate that performance is an important concern in `pug` -- you guys are doing great work!

However, the behavior where using a variable name in a loop overrides that name in the global context is (1) very surprising, (2) makes migrating from `jade` really tricky and error-prone.

For (2), see this [migration commit](https://github.com/feross/studynotes/commit/3888b193c9e10f000450a4c6b328ed5e34c18df0) on my [medium-sized pug-powered website](https://www.apstudynotes.org/). Almost every `each` loop variable needed to be changed from e.g. `note` to `note_` or `course` to `course_` to avoid overwriting `locals.course`. Forget to do this in even one place and you have a subtle bug on that page that `pug` doesn't warn you about.

Anyways, hope this context helps.

**Comment by ForbesLindesay** [comment]
The way to fix this is _simple_ in that it just involves renaming all variables within each loop to some new local name (e.g. with a unique suffix).  Unfortunately, we don't currently parse the JavaScript AST until we have completed the process of generating the code.  To make this work, we would need to switch to a mode where we parse the JavaScript as we go, generating a babylon AST and then using babel-code-gen to generate the JavaScript.

I think the renaming solution will have to wait for the next major release, so I guess I'm ok with merging this as it might unblock a lot of people who want to upgrade.

**Comment by alubbe** [comment]
I've just thought of another approach - couldn't we save the previous value and restore at the end of the loop?

**Comment by TimothyGu** [comment]
@alubbe, see https://github.com/pugjs/pug-code-gen/pull/28#issuecomment-241448712.

**Comment by ForbesLindesay** [comment]
@alubbe It's not that we're over-writing anything, although that would also create a problem.  It's that when we analyse the code for global variables, we don't see any.  The problem is the variables don't get scoped to the loop like they used to.

**Comment by alubbe** [comment]
Ah that just compounds the complexity. Alright, let's revert it for now. Can we at least detect this case and print a message (which can be disabled) that this might be removed in 3.0?

**Comment by ForbesLindesay** [comment]
Very difficult to efficiently detect in the general case since it would essentially require running the entire static analysis of the code base for global variables twice.

**Comment by ForbesLindesay** [comment]
I've merged this for now.  We can think more carefully about this for a future release.

**Pull request merged**
